### ISSUE TITLE
Can not get recv_fd

### ISSUE THREAD

**Issue by ZhangXiaoxu** [tonysimpson/nanomsg-python#64] opened 2018-05-03 06:14 UTC
![1](https://user-images.githubusercontent.com/9027353/39561656-a0b1ed1c-4ed9-11e8-8c17-9d180f8d17d7.png)

Always receive exception, I delete the highlight part, it works. 
Any update？when？

**Comment by tonysimpson** [comment] 2018-05-03 08:12
Thanks, Do you know why that check is failing?

**Comment by ZhangXiaoxu** [comment] 2018-05-03 09:48
In x64 environment, length is 8.

**Comment by tonysimpson** [comment] 2018-05-03 10:07
Should be fixed on HEAD now. Regards.

**Closed** 2018-05-28 11:04 UTC

**Comment by codypiersall** [comment] 2018-06-05 20:23
@ZhangXiaoxu, could you give more details about the code you were running that caused this issue?  I can't reproduce it, and I think commit https://github.com/tonysimpson/nanomsg-python/commit/aed15210b2bdb68d708ec2f64e83fba8b4e3d8e1 which was in response to this issue may have broken things for 64-bit Linux and Mac.

**Comment by radiocane** [comment] 2018-12-12 15:13
Indeed, I'm 64-bit Linux and commit:aed1521 raises because ```_INT_PACKER(str('l')).size``` is 8 while ```sizeof(int)``` is 4
I also question the ```length != size``` check: I'd say, if the return value is not negative, use the returned length to correctly interpret the value inside buf and be merry.
